' Copyright (C) 2007-2011 Thies Gerken

' This file is part of ScreenshotStudio.Net.

' ScreenshotStudio.Net is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.

' ScreenshotStudio.Net is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.

' You should have received a copy of the GNU General Public License
' along with ScreenshotStudio.Net. If not, see <http://www.gnu.org/licenses/>.

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Strings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ScreenshotStudioDotNet.ScreenshotTypes.Strings", GetType(Strings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Correction.
        '''</summary>
        Friend Shared ReadOnly Property correction() As String
            Get
                Return ResourceManager.GetString("correction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter, Click.
        '''</summary>
        Friend Shared ReadOnly Property enterAndClick() As String
            Get
                Return ResourceManager.GetString("enterAndClick", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter, Double-Click.
        '''</summary>
        Friend Shared ReadOnly Property enterAndDoubleClick() As String
            Get
                Return ResourceManager.GetString("enterAndDoubleClick", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Screenshot of a FreeHand selected part of the screen.
        '''</summary>
        Friend Shared ReadOnly Property freeHandDescription() As String
            Get
                Return ResourceManager.GetString("freeHandDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FreeHand.
        '''</summary>
        Friend Shared ReadOnly Property freeHandName() As String
            Get
                Return ResourceManager.GetString("freeHandName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Screenshot of the whole screen.
        '''</summary>
        Friend Shared ReadOnly Property fullscreenDescription() As String
            Get
                Return ResourceManager.GetString("fullscreenDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FullScreen.
        '''</summary>
        Friend Shared ReadOnly Property fullscreenName() As String
            Get
                Return ResourceManager.GetString("fullscreenName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Move Selection.
        '''</summary>
        Friend Shared ReadOnly Property moveSelection() As String
            Get
                Return ResourceManager.GetString("moveSelection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Selection.
        '''</summary>
        Friend Shared ReadOnly Property newSelection() As String
            Get
                Return ResourceManager.GetString("newSelection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Screenshot of a part of the screen, e.g. a rectangle.
        '''</summary>
        Friend Shared ReadOnly Property regionDescription() As String
            Get
                Return ResourceManager.GetString("regionDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Region.
        '''</summary>
        Friend Shared ReadOnly Property regionName() As String
            Get
                Return ResourceManager.GetString("regionName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resize Selection.
        '''</summary>
        Friend Shared ReadOnly Property resizeSelection() As String
            Get
                Return ResourceManager.GetString("resizeSelection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Screenshot of a web page.
        '''</summary>
        Friend Shared ReadOnly Property websiteDescription() As String
            Get
                Return ResourceManager.GetString("websiteDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Website.
        '''</summary>
        Friend Shared ReadOnly Property websiteName() As String
            Get
                Return ResourceManager.GetString("websiteName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Screenshot of a window.
        '''</summary>
        Friend Shared ReadOnly Property windowDescription() As String
            Get
                Return ResourceManager.GetString("windowDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Window.
        '''</summary>
        Friend Shared ReadOnly Property windowName() As String
            Get
                Return ResourceManager.GetString("windowName", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
