' Copyright (C) 2007-2011 Thies Gerken

' This file is part of ScreenshotStudio.Net.

' ScreenshotStudio.Net is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.

' ScreenshotStudio.Net is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.

' You should have received a copy of the GNU General Public License
' along with ScreenshotStudio.Net. If not, see <http://www.gnu.org/licenses/>.

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Strings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ScreenshotStudioDotNet.Strings", GetType(Strings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to drag to move.
        '''</summary>
        Friend Shared ReadOnly Property dragToMove() As String
            Get
                Return ResourceManager.GetString("dragToMove", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Height: .
        '''</summary>
        Friend Shared ReadOnly Property height() As String
            Get
                Return ResourceManager.GetString("height", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Macros.
        '''</summary>
        Friend Shared ReadOnly Property macros() As String
            Get
                Return ResourceManager.GetString("macros", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Macro completed.
        '''</summary>
        Friend Shared ReadOnly Property MacroTaken() As String
            Get
                Return ResourceManager.GetString("MacroTaken", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All Screenshots have been taken..
        '''</summary>
        Friend Shared ReadOnly Property MacroTakenText() As String
            Get
                Return ResourceManager.GetString("MacroTakenText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Displays.
        '''</summary>
        Friend Shared ReadOnly Property monitors() As String
            Get
                Return ResourceManager.GetString("monitors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Output.
        '''</summary>
        Friend Shared ReadOnly Property Output() As String
            Get
                Return ResourceManager.GetString("Output", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Outputs.
        '''</summary>
        Friend Shared ReadOnly Property outputs() As String
            Get
                Return ResourceManager.GetString("outputs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Screenshot Taken.
        '''</summary>
        Friend Shared ReadOnly Property ScreenshotTaken() As String
            Get
                Return ResourceManager.GetString("ScreenshotTaken", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Output used.
        '''</summary>
        Friend Shared ReadOnly Property ScreenshotTakenNoOutput() As String
            Get
                Return ResourceManager.GetString("ScreenshotTakenNoOutput", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show.
        '''</summary>
        Friend Shared ReadOnly Property show() As String
            Get
                Return ResourceManager.GetString("show", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Screenshottypes.
        '''</summary>
        Friend Shared ReadOnly Property types() As String
            Get
                Return ResourceManager.GetString("types", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Width: .
        '''</summary>
        Friend Shared ReadOnly Property width() As String
            Get
                Return ResourceManager.GetString("width", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
