' Copyright (C) 2007-2011 Thies Gerken

' This file is part of ScreenshotStudio.Net.

' ScreenshotStudio.Net is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.

' ScreenshotStudio.Net is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.

' You should have received a copy of the GNU General Public License
' along with ScreenshotStudio.Net. If not, see <http://www.gnu.org/licenses/>.

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Strings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ScreenshotStudioDotNet.Outputs.General.Strings", GetType(Strings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Output canceled.
        '''</summary>
        Friend Shared ReadOnly Property canceled() As String
            Get
                Return ResourceManager.GetString("canceled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copies the Screenshot to the Clipboard.
        '''</summary>
        Friend Shared ReadOnly Property clipboardDesc() As String
            Get
                Return ResourceManager.GetString("clipboardDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clipboard.
        '''</summary>
        Friend Shared ReadOnly Property clipboardName() As String
            Get
                Return ResourceManager.GetString("clipboardName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sends the Screenshot via Email.
        '''</summary>
        Friend Shared ReadOnly Property emailDesc() As String
            Get
                Return ResourceManager.GetString("emailDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to E-Mail.
        '''</summary>
        Friend Shared ReadOnly Property emailName() As String
            Get
                Return ResourceManager.GetString("emailName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Uploads the Screenshot to a FTP server.
        '''</summary>
        Friend Shared ReadOnly Property ftpDesc() As String
            Get
                Return ResourceManager.GetString("ftpDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File Transfer Protocol (FTP).
        '''</summary>
        Friend Shared ReadOnly Property ftpName() As String
            Get
                Return ResourceManager.GetString("ftpName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Acquiring Link ....
        '''</summary>
        Friend Shared ReadOnly Property gettingLink() As String
            Get
                Return ResourceManager.GetString("gettingLink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Image Files.
        '''</summary>
        Friend Shared ReadOnly Property imageFiles() As String
            Get
                Return ResourceManager.GetString("imageFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Uploads the Screenshot to Imageshack.us.
        '''</summary>
        Friend Shared ReadOnly Property imageshackDesc() As String
            Get
                Return ResourceManager.GetString("imageshackDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Imageshack.us.
        '''</summary>
        Friend Shared ReadOnly Property imageshackName() As String
            Get
                Return ResourceManager.GetString("imageshackName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to minute.
        '''</summary>
        Friend Shared ReadOnly Property minute() As String
            Get
                Return ResourceManager.GetString("minute", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to minutes.
        '''</summary>
        Friend Shared ReadOnly Property minutes() As String
            Get
                Return ResourceManager.GetString("minutes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Output.
        '''</summary>
        Friend Shared ReadOnly Property noneDesc() As String
            Get
                Return ResourceManager.GetString("noneDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to None.
        '''</summary>
        Friend Shared ReadOnly Property noneName() As String
            Get
                Return ResourceManager.GetString("noneName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please wait, while your screenshot is being uploaded..
        '''</summary>
        Friend Shared ReadOnly Property pleaseWait() As String
            Get
                Return ResourceManager.GetString("pleaseWait", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saves the Screenshot under a specified filename.
        '''</summary>
        Friend Shared ReadOnly Property saveAsDesc() As String
            Get
                Return ResourceManager.GetString("saveAsDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save As.
        '''</summary>
        Friend Shared ReadOnly Property saveAsName() As String
            Get
                Return ResourceManager.GetString("saveAsName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saves the Screenshot.
        '''</summary>
        Friend Shared ReadOnly Property saveDesc() As String
            Get
                Return ResourceManager.GetString("saveDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save.
        '''</summary>
        Friend Shared ReadOnly Property saveName() As String
            Get
                Return ResourceManager.GetString("saveName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to second.
        '''</summary>
        Friend Shared ReadOnly Property second() As String
            Get
                Return ResourceManager.GetString("second", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to seconds.
        '''</summary>
        Friend Shared ReadOnly Property seconds() As String
            Get
                Return ResourceManager.GetString("seconds", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select a filename.
        '''</summary>
        Friend Shared ReadOnly Property selectFileName() As String
            Get
                Return ResourceManager.GetString("selectFileName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to and.
        '''</summary>
        Friend Shared ReadOnly Property waitAnd() As String
            Get
                Return ResourceManager.GetString("waitAnd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to left.
        '''</summary>
        Friend Shared ReadOnly Property waitLeft() As String
            Get
                Return ResourceManager.GetString("waitLeft", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to of.
        '''</summary>
        Friend Shared ReadOnly Property waitOf() As String
            Get
                Return ResourceManager.GetString("waitOf", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
